In [25]:
#importing packages
import numpy as np
import pandas as pd

In [26]:
#load dataset
dataset = pd.read_csv('C:/Users/Abarna V/Desktop/weight-height.csv')

In [27]:
dataset.head(10)


Gender     Height      Weight
0    Male  73.847017  241.893563
1    Male  68.781904  162.310473
2    Male  74.110105  212.740856
3    Male  71.730978  220.042470
4    Male  69.881796  206.349801
5    Male  67.253016  152.212156
6    Male  68.785081         NaN
7    Male  68.348516  167.971111
8    Male  67.018950  175.929440
9  Female  65.755948  137.471104

In [28]:
#Create independent and dependent variable vectors
x = dataset.iloc[:,1:3].values #Independent variable data
print(x)

[[ 73.84701702 241.8935632 ]
 [ 68.78190405 162.3104725 ]
 [ 74.11010539 212.7408556 ]
 [ 71.7309784  220.0424703 ]
 [ 69.88179586 206.3498006 ]
 [ 67.25301569 152.2121558 ]
 [ 68.78508125          nan]
 [ 68.34851551 167.9711105 ]
 [ 67.01894966 175.9294404 ]
 [ 65.75594816 137.4711041 ]
 [         nan 154.9049863 ]
 [ 64.23774197 147.2054901 ]
 [ 63.10498437 133.1482542 ]
 [ 62.78030163 145.7943741 ]
 [ 63.4731386           nan]
 [ 66.74916684 166.8803156 ]
 [ 66.52949335 149.7392078 ]
 [         nan 135.3871538 ]
 [ 64.25475995 143.3638501 ]]


In [29]:
#Dependent variable data
y = dataset.iloc[:,-3].values 
print(y)

['Male' 'Male' 'Male' 'Male' 'Male' 'Male' 'Male' 'Male' 'Male' 'Female'
 'Female' 'Female' 'Female' 'Female' 'Female' 'Female' 'Female' 'Female'
 'Female']


In [30]:
#handling missing data 
#count the number of missing valies in each column
print(dataset.isnull().sum())

Gender    0
Height    2
Weight    2
dtype: int64


In [31]:
#drop missing value records
dataset.dropna(inplace = True)
print(dataset)

    Gender     Height      Weight
0     Male  73.847017  241.893563
1     Male  68.781904  162.310473
2     Male  74.110105  212.740856
3     Male  71.730978  220.042470
4     Male  69.881796  206.349801
5     Male  67.253016  152.212156
7     Male  68.348516  167.971111
8     Male  67.018950  175.929440
9   Female  65.755948  137.471104
11  Female  64.237742  147.205490
12  Female  63.104984  133.148254
13  Female  62.780302  145.794374
15  Female  66.749167  166.880316
16  Female  66.529493  149.739208
18  Female  64.254760  143.363850


In [32]:
#Replace the missing values
# Taking care of missing data (replacing with the mean)
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

# Fitting the imputer object to the matrix of features X
imputer.fit(x[:,0:3])

# Replacing the missing data by the mean of the column
x[:,0:3] = imputer.transform(x[:,0:3])
print(x[:,0:3])


[[ 73.84701702 241.8935632 ]
 [ 68.78190405 162.3104725 ]
 [ 74.11010539 212.7408556 ]
 [ 71.7309784  220.0424703 ]
 [ 69.88179586 206.3498006 ]
 [ 67.25301569 152.2121558 ]
 [ 68.78508125 167.84380029]
 [ 68.34851551 167.9711105 ]
 [ 67.01894966 175.9294404 ]
 [ 65.75594816 137.4711041 ]
 [ 67.44958222 154.9049863 ]
 [ 64.23774197 147.2054901 ]
 [ 63.10498437 133.1482542 ]
 [ 62.78030163 145.7943741 ]
 [ 63.4731386  167.84380029]
 [ 66.74916684 166.8803156 ]
 [ 66.52949335 149.7392078 ]
 [ 67.44958222 135.3871538 ]
 [ 64.25475995 143.3638501 ]]


In [33]:
#Label Encoding
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
y=label_encoder.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
#Feature Scaling - Standardisation
from sklearn.preprocessing import StandardScaler

In [35]:
#split the training and testing dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 1)
print(x_train)

[[ 63.4731386  167.84380029]
 [ 69.88179586 206.3498006 ]
 [ 66.52949335 149.7392078 ]
 [ 68.34851551 167.9711105 ]
 [ 68.78190405 162.3104725 ]
 [ 62.78030163 145.7943741 ]
 [ 73.84701702 241.8935632 ]
 [ 64.25475995 143.3638501 ]
 [ 67.44958222 135.3871538 ]
 [ 65.75594816 137.4711041 ]
 [ 67.01894966 175.9294404 ]
 [ 63.10498437 133.1482542 ]
 [ 64.23774197 147.2054901 ]
 [ 67.25301569 152.2121558 ]]


In [36]:
print(x_test)

[[ 71.7309784  220.0424703 ]
 [ 66.74916684 166.8803156 ]
 [ 68.78508125 167.84380029]
 [ 67.44958222 154.9049863 ]
 [ 74.11010539 212.7408556 ]]


In [37]:
print(y_train)

[0 1 0 1 1 0 1 0 0 0 1 0 0 1]


In [38]:
print(y_test)

[1 0 1 0 1]
